Repository adonisjs/lucid, pull requests merged in 2022-05, with the labels that each got.

#829 Use anonymous classes for migrations
  templates/migration-alter.txt
  templates/migration-make.txt
Labels: Type: Enhancement, Priority: Low

#837 feat: `make:factory` command + `--factory` flag to `make:model`
  commands/MakeFactory.ts
  commands/MakeModel.ts
  commands/index.ts
  templates/factory.txt
  test-helpers/index.ts
  test/commands/make-factory.spec.ts
Labels: Type: Feature Request

#838 feat: add `--compact-output` on DbSeed command
  commands/DbSeed.ts
  src/TestUtils/Seeder.ts
  test/commands/db-seed.spec.ts
Labels: Type: Enhancement
